### ISSUE TITLE
can't change port 8080

### ISSUE THREAD

**Issue by jphustman** [rangle/rangle-starter#162]
I need 8080 open, so I changed server/node-server.js  to process.env.PORT || 8088 and when I npm run dev, I get "Error: listen EADDRINUSE 127.0.0.1:8080" is there a cache or something that needs cleared? 

I'm using the Angular 1 starter.

Thank you.

**Comment by SethDavenport** [comment]
In release mode (`npm start`) the nodejs server does a couple of things: it serves a client code bundle from the dist folder (generated by `npm run build`) and some REST endpoints under an `/api` route.

However in dev mode `npm run dev`, we use webpack-dev-server (on port 8080) to serve the client separately and the nodejs server (on port 3000) just serves the routes under `/api`. This is so we can benefit from webpack-dev-server's live reload features for a faster development workflow.

**Comment by SethDavenport** [comment]
If you need to keep 8080 open for something else while running in devmode, you need to change the webpack-dev-server port instead. You can do this by adding `--port 8088`  to the webpack-dev-server command in package.json

**Comment by jphustman** [comment]
Thank you this did change the port, but I'm getting a error that was still showing up before even when the port was at 8080.

```
...
   [71] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [72] ./~/ansi-regex/index.js 135 bytes {0} [built]

ERROR in ./src/index.ts
Module build failed: TypeError: this.ts.getAutomaticTypeDirectiveNames is not a function
    at State.loadTypesFromConfig (/var/www/myproject/node_modules/awesome-typescript-loader/src/host.ts:148:36)
    at new State (/var/www/myproject/node_modules/awesome-typescript-loader/src/host.ts:142:14)
    at Object.ensureInstance (/var/www/myproject/node_modules/awesome-typescript-loader/src/instance.ts:150:19)
    at compiler (/var/www/myproject/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/var/www/myproject/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi app
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 453 bytes [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 453 bytes {0} [built]
Error: ENOENT: no such file or directory, stat '/var/www/myproject/dist/index.html'
    at Error (native)
```

Is there a better place than github issues for new 'rangle-starter' user troubleshooting?

**Comment by SethDavenport** [comment]
Hmm haven't seen that before - I'll take a look Monday when I'm back from traveling.

We also have a gitter channel for the starter projects: https://gitter.im/rangle/rangle-starter

**Comment by jphustman** [comment]
Thank you, the port issue is fixed so I'll close this and head over there.
