### ISSUE TITLE
(Angular2/Typescript) TypeError: Cannot read property 'exclude' of undefined 

### ISSUE THREAD

**Issue by jphustman** [rangle/rangle-starter#211]
ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/var/www/clients/client5/web7/home/kmeservejphustman/Desktop/testing/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/var/www/clients/client5/web7/home/kmeservejphustman/Desktop/testing/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/var/www/clients/client5/web7/home/kmeservejphustman/Desktop/testing/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/var/www/clients/client5/web7/home/kmeservejphustman/Desktop/testing/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi app

ERROR in ./src/vendor.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/var/www/clients/client5/web7/home/kmeservejphustman/Desktop/testing/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/var/www/clients/client5/web7/home/kmeservejphustman/Desktop/testing/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/var/www/clients/client5/web7/home/kmeservejphustman/Desktop/testing/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/var/www/clients/client5/web7/home/kmeservejphustman/Desktop/testing/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi vendor

I think it has something to do with the Typescript version?

**Comment by qinlinxin2080** [comment]
i see the same problem

**Comment by SethDavenport** [comment]
Yes, we need to update to the latest typescript; there are some breaking changes. In the mean time you can pin your ts version to 2.0

**Comment by SethDavenport** [comment]
@winkervswbecks @bennett000: I can try to get on this on Friday unless sup sq has time before then?

**Comment by jphustman** [comment]
Yup I simply removed the ^ in the typescript dependency in package.json.

**Comment by jamesbs** [comment]
Any issues with switching to the awesome-typescript-loader 3.0.0-beta version instead?

**Comment by jackytse** [comment]
i see the same problem

**Comment by fahadhussain2** [comment]
![image](https://cloud.githubusercontent.com/assets/19908737/21609282/54cea6ca-d1e3-11e6-9f5f-015227c36f11.png)

Please help me to resolve this issue

**Comment by SethDavenport** [comment]
@jamesbs go ahead if that fixes it.

**Comment by fahadhussain2** [comment]
@SethDavenport  do u have any idea how to resolve this error?

**Comment by SethDavenport** [comment]
Pinned typescript to 2.0.10. This should be fixed now.

**Comment by fahadhussain2** [comment]
how to pinned typescript to 2.0.10 ? @SethDavenport

**Comment by SethDavenport** [comment]
@faradhussain2 go in your package.json and change the typescript version from ^2.0.3 to 2.0.10 (remember to remove the ^). Then do an npm install

**Comment by fahadhussain2** [comment]
removed the error .... thank you so much @SethDavenport  for your help

**Comment by fahadhussain2** [comment]
![image](https://cloud.githubusercontent.com/assets/19908737/22326272/c781d870-e3d3-11e6-881f-f04f1ae16f6f.png)

i found this error in "ng serve" after installing ngmaterial 2
Please help me with this error

**Comment by dilagurung** [comment]
downgrading typescript from 2.1.1 to 2.0.0 remove the error thrown by awesome-typescript-loader. 
On the other hand, jasmine used on the system throws an error and prompt to upgrade the typescript version. Trapped in loop. Need an immediate solution for it.

**Comment by AndresCL** [comment]
Still having this issue. I just followed angular 2 cli instructions:

`$ npm install -g angular2-cli` 
`$ ng2 create <app-name>`
`$ cd <app-folder>`
`$ ng2 init`
`$ ng2 serve`

> ERROR in ./src/main.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi main

ERROR in ./src/vendor.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/usr/local/lib/node_modules/angular2-cli/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi vendor

**Comment by nicraMarcin** [comment]
still the same error :/

**Comment by didacpr** [comment]
Does anyone know the problem with this error?

**Comment by Arafullahi** [comment]
@AndresCL did you get the solution ?

**Comment by lounceny2016** [comment]
I am also getting the same error. any idea on how to fix it.
